# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from urllib3._collections import HTTPHeaderDict

from rlink_client import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from rlink_client import schemas  # noqa: F401

# Query params
CallNumSchema = schemas.IntSchema
ChatSchema = schemas.StrSchema
CostSchema = schemas.IntSchema
DemoteSchema = schemas.StrSchema
DescriptionSchema = schemas.StrSchema
DisbandSchema = schemas.StrSchema
EditInfoSchema = schemas.StrSchema
EditPermissionSchema = schemas.StrSchema
FullNameSchema = schemas.StrSchema
IconSchema = schemas.StrSchema
InviteSchema = schemas.StrSchema
ItemPriceIdSchema = schemas.IntSchema
JoinPolicySchema = schemas.IntSchema
LastCallTimeSchema = schemas.StrSchema
LocStringIDSchema = schemas.IntSchema
MessageOfTheDaySchema = schemas.StrSchema
MetadataSchema = schemas.DictSchema
NameSchema = schemas.StrSchema
PaymentitemSchema = schemas.IntSchema
PermissionNameSchema = schemas.StrSchema
PromoteSchema = schemas.StrSchema
RankSchema = schemas.StrSchema
RemoveSchema = schemas.StrSchema
TagsSchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    "RequestRequiredQueryParams",
    {
        "callNum": typing.Union[
            CallNumSchema,
            decimal.Decimal,
            int,
        ],
        "chat": typing.Union[
            ChatSchema,
            str,
        ],
        "cost": typing.Union[
            CostSchema,
            decimal.Decimal,
            int,
        ],
        "demote": typing.Union[
            DemoteSchema,
            str,
        ],
        "description": typing.Union[
            DescriptionSchema,
            str,
        ],
        "disband": typing.Union[
            DisbandSchema,
            str,
        ],
        "editInfo": typing.Union[
            EditInfoSchema,
            str,
        ],
        "editPermission": typing.Union[
            EditPermissionSchema,
            str,
        ],
        "fullName": typing.Union[
            FullNameSchema,
            str,
        ],
        "icon": typing.Union[
            IconSchema,
            str,
        ],
        "invite": typing.Union[
            InviteSchema,
            str,
        ],
        "itemPrice_id": typing.Union[
            ItemPriceIdSchema,
            decimal.Decimal,
            int,
        ],
        "joinPolicy": typing.Union[
            JoinPolicySchema,
            decimal.Decimal,
            int,
        ],
        "lastCallTime": typing.Union[
            LastCallTimeSchema,
            str,
        ],
        "locStringID": typing.Union[
            LocStringIDSchema,
            decimal.Decimal,
            int,
        ],
        "messageOfTheDay": typing.Union[
            MessageOfTheDaySchema,
            str,
        ],
        "metadata": typing.Union[
            MetadataSchema,
            dict,
            frozendict.frozendict,
        ],
        "name": typing.Union[
            NameSchema,
            str,
        ],
        "paymentitem": typing.Union[
            PaymentitemSchema,
            decimal.Decimal,
            int,
        ],
        "permissionName": typing.Union[
            PermissionNameSchema,
            str,
        ],
        "promote": typing.Union[
            PromoteSchema,
            str,
        ],
        "rank": typing.Union[
            RankSchema,
            str,
        ],
        "remove": typing.Union[
            RemoveSchema,
            str,
        ],
        "tags": typing.Union[
            TagsSchema,
            str,
        ],
    },
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    "RequestOptionalQueryParams", {}, total=False
)

class RequestQueryParams(
    RequestRequiredQueryParams, RequestOptionalQueryParams
):
    pass

request_query_call_num = api_client.QueryParameter(
    name="callNum",
    style=api_client.ParameterStyle.FORM,
    schema=CallNumSchema,
    required=True,
    explode=True,
)
request_query_chat = api_client.QueryParameter(
    name="chat",
    style=api_client.ParameterStyle.FORM,
    schema=ChatSchema,
    required=True,
    explode=True,
)
request_query_cost = api_client.QueryParameter(
    name="cost",
    style=api_client.ParameterStyle.FORM,
    schema=CostSchema,
    required=True,
    explode=True,
)
request_query_demote = api_client.QueryParameter(
    name="demote",
    style=api_client.ParameterStyle.FORM,
    schema=DemoteSchema,
    required=True,
    explode=True,
)
request_query_description = api_client.QueryParameter(
    name="description",
    style=api_client.ParameterStyle.FORM,
    schema=DescriptionSchema,
    required=True,
    explode=True,
)
request_query_disband = api_client.QueryParameter(
    name="disband",
    style=api_client.ParameterStyle.FORM,
    schema=DisbandSchema,
    required=True,
    explode=True,
)
request_query_edit_info = api_client.QueryParameter(
    name="editInfo",
    style=api_client.ParameterStyle.FORM,
    schema=EditInfoSchema,
    required=True,
    explode=True,
)
request_query_edit_permission = api_client.QueryParameter(
    name="editPermission",
    style=api_client.ParameterStyle.FORM,
    schema=EditPermissionSchema,
    required=True,
    explode=True,
)
request_query_full_name = api_client.QueryParameter(
    name="fullName",
    style=api_client.ParameterStyle.FORM,
    schema=FullNameSchema,
    required=True,
    explode=True,
)
request_query_icon = api_client.QueryParameter(
    name="icon",
    style=api_client.ParameterStyle.FORM,
    schema=IconSchema,
    required=True,
    explode=True,
)
request_query_invite = api_client.QueryParameter(
    name="invite",
    style=api_client.ParameterStyle.FORM,
    schema=InviteSchema,
    required=True,
    explode=True,
)
request_query_item_price_id = api_client.QueryParameter(
    name="itemPrice_id",
    style=api_client.ParameterStyle.FORM,
    schema=ItemPriceIdSchema,
    required=True,
    explode=True,
)
request_query_join_policy = api_client.QueryParameter(
    name="joinPolicy",
    style=api_client.ParameterStyle.FORM,
    schema=JoinPolicySchema,
    required=True,
    explode=True,
)
request_query_last_call_time = api_client.QueryParameter(
    name="lastCallTime",
    style=api_client.ParameterStyle.FORM,
    schema=LastCallTimeSchema,
    required=True,
    explode=True,
)
request_query_loc_string_id = api_client.QueryParameter(
    name="locStringID",
    style=api_client.ParameterStyle.FORM,
    schema=LocStringIDSchema,
    required=True,
    explode=True,
)
request_query_message_of_the_day = api_client.QueryParameter(
    name="messageOfTheDay",
    style=api_client.ParameterStyle.FORM,
    schema=MessageOfTheDaySchema,
    required=True,
    explode=True,
)
request_query_metadata = api_client.QueryParameter(
    name="metadata",
    style=api_client.ParameterStyle.FORM,
    schema=MetadataSchema,
    required=True,
    explode=True,
)
request_query_name = api_client.QueryParameter(
    name="name",
    style=api_client.ParameterStyle.FORM,
    schema=NameSchema,
    required=True,
    explode=True,
)
request_query_paymentitem = api_client.QueryParameter(
    name="paymentitem",
    style=api_client.ParameterStyle.FORM,
    schema=PaymentitemSchema,
    required=True,
    explode=True,
)
request_query_permission_name = api_client.QueryParameter(
    name="permissionName",
    style=api_client.ParameterStyle.FORM,
    schema=PermissionNameSchema,
    required=True,
    explode=True,
)
request_query_promote = api_client.QueryParameter(
    name="promote",
    style=api_client.ParameterStyle.FORM,
    schema=PromoteSchema,
    required=True,
    explode=True,
)
request_query_rank = api_client.QueryParameter(
    name="rank",
    style=api_client.ParameterStyle.FORM,
    schema=RankSchema,
    required=True,
    explode=True,
)
request_query_remove = api_client.QueryParameter(
    name="remove",
    style=api_client.ParameterStyle.FORM,
    schema=RemoveSchema,
    required=True,
    explode=True,
)
request_query_tags = api_client.QueryParameter(
    name="tags",
    style=api_client.ParameterStyle.FORM,
    schema=TagsSchema,
    required=True,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = schemas.AnyTypeSchema

@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[SchemaFor200ResponseBodyApplicationJson,]
    headers: schemas.Unset = schemas.unset

_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    content={
        "application/json": api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson
        ),
    },
)
_all_accept_content_types = ("application/json",)

class BaseApi(api_client.Api):
    @typing.overload
    def _game_clan_create_oapg(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: typing_extensions.Literal[False] = ...,
    ) -> typing.Union[ApiResponseFor200,]: ...
    @typing.overload
    def _game_clan_create_oapg(
        self,
        skip_deserialization: typing_extensions.Literal[True],
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
    ) -> api_client.ApiResponseWithoutDeserialization: ...
    @typing.overload
    def _game_clan_create_oapg(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = ...,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]: ...
    def _game_clan_create_oapg(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ):
        """
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value

        prefix_separator_iterator = None
        for parameter in (
            request_query_call_num,
            request_query_chat,
            request_query_cost,
            request_query_demote,
            request_query_description,
            request_query_disband,
            request_query_edit_info,
            request_query_edit_permission,
            request_query_full_name,
            request_query_icon,
            request_query_invite,
            request_query_item_price_id,
            request_query_join_policy,
            request_query_last_call_time,
            request_query_loc_string_id,
            request_query_message_of_the_day,
            request_query_metadata,
            request_query_name,
            request_query_paymentitem,
            request_query_permission_name,
            request_query_promote,
            request_query_rank,
            request_query_remove,
            request_query_tags,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = (
                    parameter.get_prefix_separator_iterator()
                )
            serialized_data = parameter.serialize(
                parameter_data, prefix_separator_iterator
            )
            for serialized_value in serialized_data.values():
                used_path += serialized_value

        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add("Accept", accept_content_type)

        response = self.api_client.call_api(
            resource_path=used_path,
            method="post".upper(),
            headers=_headers,
            auth_settings=_auth,
            stream=stream,
            timeout=timeout,
        )

        if skip_deserialization:
            api_response = api_client.ApiResponseWithoutDeserialization(
                response=response
            )
        else:
            response_for_status = _status_code_to_response.get(
                str(response.status)
            )
            if response_for_status:
                api_response = response_for_status.deserialize(
                    response, self.api_client.configuration
                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response
                )

        if not 200 <= response.status <= 299:
            raise exceptions.ApiException(
                status=response.status,
                reason=response.reason,
                api_response=api_response,
            )

        return api_response

class GameClanCreate(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    @typing.overload
    def game_clan_create(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: typing_extensions.Literal[False] = ...,
    ) -> typing.Union[ApiResponseFor200,]: ...
    @typing.overload
    def game_clan_create(
        self,
        skip_deserialization: typing_extensions.Literal[True],
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
    ) -> api_client.ApiResponseWithoutDeserialization: ...
    @typing.overload
    def game_clan_create(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = ...,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]: ...
    def game_clan_create(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ):
        return self._game_clan_create_oapg(
            query_params=query_params,
            accept_content_types=accept_content_types,
            stream=stream,
            timeout=timeout,
            skip_deserialization=skip_deserialization,
        )

class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    @typing.overload
    def post(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: typing_extensions.Literal[False] = ...,
    ) -> typing.Union[ApiResponseFor200,]: ...
    @typing.overload
    def post(
        self,
        skip_deserialization: typing_extensions.Literal[True],
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
    ) -> api_client.ApiResponseWithoutDeserialization: ...
    @typing.overload
    def post(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = ...,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]: ...
    def post(
        self,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ):
        return self._game_clan_create_oapg(
            query_params=query_params,
            accept_content_types=accept_content_types,
            stream=stream,
            timeout=timeout,
            skip_deserialization=skip_deserialization,
        )
