# coding: utf-8

"""
    World's Edge API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 24.11.01
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rlink_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_community_clan_find(self) -> None:
        """Test case for community_clan_find

        """
        pass

    def test_community_find_advertisements(self) -> None:
        """Test case for community_find_advertisements

        """
        pass

    def test_community_get_achievements(self) -> None:
        """Test case for community_get_achievements

        """
        pass

    def test_community_get_available_achievements(self) -> None:
        """Test case for community_get_available_achievements

        """
        pass

    def test_community_get_available_community_events(self) -> None:
        """Test case for community_get_available_community_events

        """
        pass

    def test_community_get_available_leaderboards(self) -> None:
        """Test case for community_get_available_leaderboards

        """
        pass

    def test_community_get_avatar_stat_for_profile(self) -> None:
        """Test case for community_get_avatar_stat_for_profile

        """
        pass

    def test_community_get_clan_info_full(self) -> None:
        """Test case for community_get_clan_info_full

        """
        pass

    def test_community_get_inventory_by_profile_ids(self) -> None:
        """Test case for community_get_inventory_by_profile_ids

        """
        pass

    def test_community_get_leaderboard2(self) -> None:
        """Test case for community_get_leaderboard2

        """
        pass

    def test_community_get_personal_stat(self) -> None:
        """Test case for community_get_personal_stat

        """
        pass

    def test_community_get_recent_match_history(self) -> None:
        """Test case for community_get_recent_match_history

        """
        pass

    def test_community_news_get_news(self) -> None:
        """Test case for community_news_get_news

        """
        pass

    def test_community_proxy_steam_user_request(self) -> None:
        """Test case for community_proxy_steam_user_request

        """
        pass

    def test_game_account_find_profiles(self) -> None:
        """Test case for game_account_find_profiles

        """
        pass

    def test_game_account_find_profiles_by_platform_id(self) -> None:
        """Test case for game_account_find_profiles_by_platform_id

        """
        pass

    def test_game_account_get_profile_name(self) -> None:
        """Test case for game_account_get_profile_name

        """
        pass

    def test_game_account_get_profile_property(self) -> None:
        """Test case for game_account_get_profile_property

        """
        pass

    def test_game_account_set_avatar_metadata(self) -> None:
        """Test case for game_account_set_avatar_metadata

        """
        pass

    def test_game_account_set_language(self) -> None:
        """Test case for game_account_set_language

        """
        pass

    def test_game_achievement_get_achievements(self) -> None:
        """Test case for game_achievement_get_achievements

        """
        pass

    def test_game_achievement_get_available_achievements(self) -> None:
        """Test case for game_achievement_get_available_achievements

        """
        pass

    def test_game_achievement_sync_stats(self) -> None:
        """Test case for game_achievement_sync_stats

        """
        pass

    def test_game_advertisement_find_advertisements(self) -> None:
        """Test case for game_advertisement_find_advertisements

        """
        pass

    def test_game_advertisement_find_observable_advertisements_get(self) -> None:
        """Test case for game_advertisement_find_observable_advertisements_get

        """
        pass

    def test_game_advertisement_find_observable_advertisements_post(self) -> None:
        """Test case for game_advertisement_find_observable_advertisements_post

        """
        pass

    def test_game_advertisement_get_advertisements(self) -> None:
        """Test case for game_advertisement_get_advertisements

        """
        pass

    def test_game_advertisement_get_lan_advertisements(self) -> None:
        """Test case for game_advertisement_get_lan_advertisements

        """
        pass

    def test_game_advertisement_host(self) -> None:
        """Test case for game_advertisement_host

        """
        pass

    def test_game_advertisement_join(self) -> None:
        """Test case for game_advertisement_join

        """
        pass

    def test_game_advertisement_leave(self) -> None:
        """Test case for game_advertisement_leave

        """
        pass

    def test_game_advertisement_start_observing(self) -> None:
        """Test case for game_advertisement_start_observing

        """
        pass

    def test_game_advertisement_stop_observing(self) -> None:
        """Test case for game_advertisement_stop_observing

        """
        pass

    def test_game_advertisement_update(self) -> None:
        """Test case for game_advertisement_update

        """
        pass

    def test_game_advertisement_update_platform_lobby_id(self) -> None:
        """Test case for game_advertisement_update_platform_lobby_id

        """
        pass

    def test_game_advertisement_update_state(self) -> None:
        """Test case for game_advertisement_update_state

        """
        pass

    def test_game_advertisement_update_tags(self) -> None:
        """Test case for game_advertisement_update_tags

        """
        pass

    def test_game_automatch2_get_automatch_map(self) -> None:
        """Test case for game_automatch2_get_automatch_map

        """
        pass

    def test_game_automatch2_polling(self) -> None:
        """Test case for game_automatch2_polling

        """
        pass

    def test_game_automatch2_stop_polling(self) -> None:
        """Test case for game_automatch2_stop_polling

        """
        pass

    def test_game_automatch2_update_status(self) -> None:
        """Test case for game_automatch2_update_status

        """
        pass

    def test_game_automatch_get_automatch_map(self) -> None:
        """Test case for game_automatch_get_automatch_map

        """
        pass

    def test_game_challenge_get_challenge_progress(self) -> None:
        """Test case for game_challenge_get_challenge_progress

        """
        pass

    def test_game_challenge_get_challenge_progress_by_profile_id(self) -> None:
        """Test case for game_challenge_get_challenge_progress_by_profile_id

        """
        pass

    def test_game_challenge_get_challenges(self) -> None:
        """Test case for game_challenge_get_challenges

        """
        pass

    def test_game_challenge_update_progress_batched(self) -> None:
        """Test case for game_challenge_update_progress_batched

        """
        pass

    def test_game_chat_delete_offline_message(self) -> None:
        """Test case for game_chat_delete_offline_message

        """
        pass

    def test_game_chat_get_chat_channels(self) -> None:
        """Test case for game_chat_get_chat_channels

        """
        pass

    def test_game_chat_get_offline_messages(self) -> None:
        """Test case for game_chat_get_offline_messages

        """
        pass

    def test_game_clan_apply(self) -> None:
        """Test case for game_clan_apply

        """
        pass

    def test_game_clan_create(self) -> None:
        """Test case for game_clan_create

        """
        pass

    def test_game_clan_disband(self) -> None:
        """Test case for game_clan_disband

        """
        pass

    def test_game_clan_find(self) -> None:
        """Test case for game_clan_find

        """
        pass

    def test_game_clan_get_clan(self) -> None:
        """Test case for game_clan_get_clan

        """
        pass

    def test_game_clan_get_clan_info_full(self) -> None:
        """Test case for game_clan_get_clan_info_full

        """
        pass

    def test_game_clan_update(self) -> None:
        """Test case for game_clan_update

        """
        pass

    def test_game_cloud_get_file_url_get(self) -> None:
        """Test case for game_cloud_get_file_url_get

        """
        pass

    def test_game_cloud_get_file_url_post(self) -> None:
        """Test case for game_cloud_get_file_url_post

        """
        pass

    def test_game_cloud_get_temp_credentials(self) -> None:
        """Test case for game_cloud_get_temp_credentials

        """
        pass

    def test_game_community_event_get_available_community_events(self) -> None:
        """Test case for game_community_event_get_available_community_events

        """
        pass

    def test_game_community_event_get_event_challenge_progress(self) -> None:
        """Test case for game_community_event_get_event_challenge_progress

        """
        pass

    def test_game_community_event_get_event_stats(self) -> None:
        """Test case for game_community_event_get_event_stats

        """
        pass

    def test_game_invitation_cancel_invitation(self) -> None:
        """Test case for game_invitation_cancel_invitation

        """
        pass

    def test_game_invitation_extend_invitation(self) -> None:
        """Test case for game_invitation_extend_invitation

        """
        pass

    def test_game_item_detach_items(self) -> None:
        """Test case for game_item_detach_items

        """
        pass

    def test_game_item_get_inventory_by_profile_ids(self) -> None:
        """Test case for game_item_get_inventory_by_profile_ids

        """
        pass

    def test_game_item_get_item_bundle_items_json(self) -> None:
        """Test case for game_item_get_item_bundle_items_json

        """
        pass

    def test_game_item_get_item_definitions_json(self) -> None:
        """Test case for game_item_get_item_definitions_json

        """
        pass

    def test_game_item_get_item_loadouts(self) -> None:
        """Test case for game_item_get_item_loadouts

        """
        pass

    def test_game_item_get_item_prices(self) -> None:
        """Test case for game_item_get_item_prices

        """
        pass

    def test_game_item_get_level_rewards_table_json(self) -> None:
        """Test case for game_item_get_level_rewards_table_json

        """
        pass

    def test_game_item_get_personalized_sale_items(self) -> None:
        """Test case for game_item_get_personalized_sale_items

        """
        pass

    def test_game_item_get_scheduled_sale_and_items(self) -> None:
        """Test case for game_item_get_scheduled_sale_and_items

        """
        pass

    def test_game_item_move_charges(self) -> None:
        """Test case for game_item_move_charges

        """
        pass

    def test_game_item_move_item(self) -> None:
        """Test case for game_item_move_item

        """
        pass

    def test_game_item_open_item_pack(self) -> None:
        """Test case for game_item_open_item_pack

        """
        pass

    def test_game_item_sign_item(self) -> None:
        """Test case for game_item_sign_item

        """
        pass

    def test_game_item_update_item_attributes(self) -> None:
        """Test case for game_item_update_item_attributes

        """
        pass

    def test_game_leaderboard_get_available_leaderboards(self) -> None:
        """Test case for game_leaderboard_get_available_leaderboards

        """
        pass

    def test_game_leaderboard_get_leaderboard(self) -> None:
        """Test case for game_leaderboard_get_leaderboard

        """
        pass

    def test_game_leaderboard_get_party_stat(self) -> None:
        """Test case for game_leaderboard_get_party_stat

        """
        pass

    def test_game_leaderboard_get_personal_stat(self) -> None:
        """Test case for game_leaderboard_get_personal_stat

        """
        pass

    def test_game_leaderboard_get_recent_match_history_get(self) -> None:
        """Test case for game_leaderboard_get_recent_match_history_get

        """
        pass

    def test_game_leaderboard_get_recent_match_history_post(self) -> None:
        """Test case for game_leaderboard_get_recent_match_history_post

        """
        pass

    def test_game_leaderboard_get_recent_match_single_player_history(self) -> None:
        """Test case for game_leaderboard_get_recent_match_single_player_history

        """
        pass

    def test_game_leaderboard_get_stat_groups_by_profile_ids(self) -> None:
        """Test case for game_leaderboard_get_stat_groups_by_profile_ids

        """
        pass

    def test_game_leaderboard_get_stats_for_leaderboard_by_profile_name(self) -> None:
        """Test case for game_leaderboard_get_stats_for_leaderboard_by_profile_name

        """
        pass

    def test_game_leaderboard_set_avatar_stat_values(self) -> None:
        """Test case for game_leaderboard_set_avatar_stat_values

        """
        pass

    def test_game_login_logout(self) -> None:
        """Test case for game_login_logout

        """
        pass

    def test_game_login_platform_login(self) -> None:
        """Test case for game_login_platform_login

        """
        pass

    def test_game_login_read_session(self) -> None:
        """Test case for game_login_read_session

        """
        pass

    def test_game_news_get_news(self) -> None:
        """Test case for game_news_get_news

        """
        pass

    def test_game_party_create_or_report_single_player(self) -> None:
        """Test case for game_party_create_or_report_single_player

        """
        pass

    def test_game_party_finalize_replay_upload(self) -> None:
        """Test case for game_party_finalize_replay_upload

        """
        pass

    def test_game_party_peer_add(self) -> None:
        """Test case for game_party_peer_add

        """
        pass

    def test_game_party_peer_update(self) -> None:
        """Test case for game_party_peer_update

        """
        pass

    def test_game_party_report_match(self) -> None:
        """Test case for game_party_report_match

        """
        pass

    def test_game_party_send_match_chat(self) -> None:
        """Test case for game_party_send_match_chat

        """
        pass

    def test_game_playerreport_report_user(self) -> None:
        """Test case for game_playerreport_report_user

        """
        pass

    def test_game_relationship_clear_relationship(self) -> None:
        """Test case for game_relationship_clear_relationship

        """
        pass

    def test_game_relationship_get_presence_data(self) -> None:
        """Test case for game_relationship_get_presence_data

        """
        pass

    def test_game_relationship_get_relationships(self) -> None:
        """Test case for game_relationship_get_relationships

        """
        pass

    def test_game_relationship_ignore(self) -> None:
        """Test case for game_relationship_ignore

        """
        pass

    def test_game_relationship_set_presence(self) -> None:
        """Test case for game_relationship_set_presence

        """
        pass

    def test_game_relationship_set_presence_property(self) -> None:
        """Test case for game_relationship_set_presence_property

        """
        pass


if __name__ == '__main__':
    unittest.main()
