# coding: utf-8

"""
    Relic Link API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 23.03.01
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.community_clan_find.get import CommunityClanFind
from openapi_client.paths.community_advertisement_find_advertisements.get import CommunityFindAdvertisements
from openapi_client.paths.community_achievement_get_achievements.get import CommunityGetAchievements
from openapi_client.paths.community_achievement_get_available_achievements.get import CommunityGetAvailableAchievements
from openapi_client.paths.community_community_event_get_available_community_events.get import CommunityGetAvailableCommunityEvents
from openapi_client.paths.community_leaderboard_get_available_leaderboards.get import CommunityGetAvailableLeaderboards
from openapi_client.paths.community_leaderboard_get_avatar_stat_for_profile.get import CommunityGetAvatarStatForProfile
from openapi_client.paths.community_clan_get_clan_info_full.get import CommunityGetClanInfoFull
from openapi_client.paths.community_item_get_inventory_by_profile_ids.get import CommunityGetInventoryByProfileIds
from openapi_client.paths.community_leaderboard_get_leaderboard2.get import CommunityGetLeaderboard2
from openapi_client.paths.community_leaderboard_get_personal_stat.get import CommunityGetPersonalStat
from openapi_client.paths.community_leaderboard_get_recent_match_history.get import CommunityGetRecentMatchHistory
from openapi_client.paths.community_news_get_news.get import CommunityNewsGetNews
from openapi_client.paths.community_external_proxysteamuserrequest.get import CommunityProxySteamUserRequest
from openapi_client.paths.game_account_find_profiles.get import GameAccountFindProfiles
from openapi_client.paths.game_account_find_profiles_by_platform_id.get import GameAccountFindProfilesByPlatformId
from openapi_client.paths.game_account_get_profile_name.get import GameAccountGetProfileName
from openapi_client.paths.game_account_get_profile_property.get import GameAccountGetProfileProperty
from openapi_client.paths.game_account_set_avatar_metadata.post import GameAccountSetAvatarMetadata
from openapi_client.paths.game_account_set_language.post import GameAccountSetLanguage
from openapi_client.paths.game_achievement_get_achievements.get import GameAchievementGetAchievements
from openapi_client.paths.game_achievement_get_available_achievements.get import GameAchievementGetAvailableAchievements
from openapi_client.paths.game_achievement_sync_stats.post import GameAchievementSyncStats
from openapi_client.paths.game_advertisement_find_advertisements.get import GameAdvertisementFindAdvertisements
from openapi_client.paths.game_advertisement_find_observable_advertisements.get import GameAdvertisementFindObservableAdvertisementsGet
from openapi_client.paths.game_advertisement_find_observable_advertisements.post import GameAdvertisementFindObservableAdvertisementsPost
from openapi_client.paths.game_advertisement_get_advertisements.get import GameAdvertisementGetAdvertisements
from openapi_client.paths.game_advertisement_get_lan_advertisements.get import GameAdvertisementGetLanAdvertisements
from openapi_client.paths.game_advertisement_host.post import GameAdvertisementHost
from openapi_client.paths.game_advertisement_join.post import GameAdvertisementJoin
from openapi_client.paths.game_advertisement_leave.post import GameAdvertisementLeave
from openapi_client.paths.game_advertisement_start_observing.post import GameAdvertisementStartObserving
from openapi_client.paths.game_advertisement_stop_observing.post import GameAdvertisementStopObserving
from openapi_client.paths.game_advertisement_update.post import GameAdvertisementUpdate
from openapi_client.paths.game_advertisement_update_platform_lobby_id.post import GameAdvertisementUpdatePlatformLobbyId
from openapi_client.paths.game_advertisement_update_state.post import GameAdvertisementUpdateState
from openapi_client.paths.game_advertisement_update_tags.post import GameAdvertisementUpdateTags
from openapi_client.paths.game_automatch2_get_automatch_map.get import GameAutomatch2GetAutomatchMap
from openapi_client.paths.game_automatch2_polling.post import GameAutomatch2Polling
from openapi_client.paths.game_automatch2_stoppolling.post import GameAutomatch2StopPolling
from openapi_client.paths.game_automatch2_update_status.post import GameAutomatch2UpdateStatus
from openapi_client.paths.game_automatch_get_automatch_map.get import GameAutomatchGetAutomatchMap
from openapi_client.paths.game_challenge_get_challenge_progress.get import GameChallengeGetChallengeProgress
from openapi_client.paths.game_challenge_get_challenge_progress_by_profile_id.get import GameChallengeGetChallengeProgressByProfileId
from openapi_client.paths.game_challenge_get_challenges.get import GameChallengeGetChallenges
from openapi_client.paths.game_challenge_update_progress_batched.post import GameChallengeUpdateProgressBatched
from openapi_client.paths.game_chat_delete_offline_message.post import GameChatDeleteOfflineMessage
from openapi_client.paths.game_chat_get_chat_channels.get import GameChatGetChatChannels
from openapi_client.paths.game_chat_get_offline_messages.get import GameChatGetOfflineMessages
from openapi_client.paths.game_clan_apply.post import GameClanApply
from openapi_client.paths.game_clan_create.post import GameClanCreate
from openapi_client.paths.game_clan_disband.post import GameClanDisband
from openapi_client.paths.game_clan_find.get import GameClanFind
from openapi_client.paths.game_clan_get_clan.get import GameClanGetClan
from openapi_client.paths.game_clan_get_clan_info_full.get import GameClanGetClanInfoFull
from openapi_client.paths.game_clan_update.post import GameClanUpdate
from openapi_client.paths.game_cloud_get_file_url.get import GameCloudGetFileUrlGet
from openapi_client.paths.game_cloud_get_file_url.post import GameCloudGetFileUrlPost
from openapi_client.paths.game_cloud_get_temp_credentials.get import GameCloudGetTempCredentials
from openapi_client.paths.game_community_event_get_available_community_events.get import GameCommunityEventGetAvailableCommunityEvents
from openapi_client.paths.game_community_event_get_event_challenge_progress.get import GameCommunityEventGetEventChallengeProgress
from openapi_client.paths.game_community_event_get_event_stats.get import GameCommunityEventGetEventStats
from openapi_client.paths.game_invitation_cancel_invitation.post import GameInvitationCancelInvitation
from openapi_client.paths.game_invitation_extend_invitation.post import GameInvitationExtendInvitation
from openapi_client.paths.game_item_detach_items.post import GameItemDetachItems
from openapi_client.paths.game_item_get_inventory_by_profile_ids.get import GameItemGetInventoryByProfileIds
from openapi_client.paths.game_item_get_item_bundle_items_json.get import GameItemGetItemBundleItemsJson
from openapi_client.paths.game_item_get_item_definitions_json.get import GameItemGetItemDefinitionsJson
from openapi_client.paths.game_item_get_item_loadouts.get import GameItemGetItemLoadouts
from openapi_client.paths.game_item_get_item_prices.get import GameItemGetItemPrices
from openapi_client.paths.game_item_get_level_rewards_table_json.get import GameItemGetLevelRewardsTableJson
from openapi_client.paths.game_item_get_personalized_sale_items.get import GameItemGetPersonalizedSaleItems
from openapi_client.paths.game_item_get_scheduled_sale_and_items.get import GameItemGetScheduledSaleAndItems
from openapi_client.paths.game_item_move_charges.post import GameItemMoveCharges
from openapi_client.paths.game_item_move_item.post import GameItemMoveItem
from openapi_client.paths.game_item_open_item_pack.post import GameItemOpenItemPack
from openapi_client.paths.game_item_sign_items.post import GameItemSignItem
from openapi_client.paths.game_item_update_item_attributes.post import GameItemUpdateItemAttributes
from openapi_client.paths.game_leaderboard_get_available_leaderboards.get import GameLeaderboardGetAvailableLeaderboards
from openapi_client.paths.game_leaderboard_get_leader_board.get import GameLeaderboardGetLeaderboard
from openapi_client.paths.game_leaderboard_get_party_stat.get import GameLeaderboardGetPartyStat
from openapi_client.paths.game_leaderboard_get_personal_stat.get import GameLeaderboardGetPersonalStat
from openapi_client.paths.game_leaderboard_get_recent_match_history.get import GameLeaderboardGetRecentMatchHistoryGet
from openapi_client.paths.game_leaderboard_get_recent_match_history.post import GameLeaderboardGetRecentMatchHistoryPost
from openapi_client.paths.game_leaderboard_get_recent_match_single_player_history.get import GameLeaderboardGetRecentMatchSinglePlayerHistory
from openapi_client.paths.game_leaderboard_get_stat_groups_by_profile_ids.get import GameLeaderboardGetStatGroupsByProfileIds
from openapi_client.paths.game_leaderboard_get_stats_for_leaderboard_by_profile_name.get import GameLeaderboardGetStatsForLeaderboardByProfileName
from openapi_client.paths.game_leaderboard_set_avatar_stat_values.post import GameLeaderboardSetAvatarStatValues
from openapi_client.paths.game_login_logout.post import GameLoginLogout
from openapi_client.paths.game_login_platformlogin.post import GameLoginPlatformLogin
from openapi_client.paths.game_login_read_session.post import GameLoginReadSession
from openapi_client.paths.game_news_get_news.get import GameNewsGetNews
from openapi_client.paths.game_party_create_or_report_single_player.post import GamePartyCreateOrReportSinglePlayer
from openapi_client.paths.game_party_finalize_replay_upload.post import GamePartyFinalizeReplayUpload
from openapi_client.paths.game_party_peer_add.post import GamePartyPeerAdd
from openapi_client.paths.game_party_peer_update.post import GamePartyPeerUpdate
from openapi_client.paths.game_party_report_match.post import GamePartyReportMatch
from openapi_client.paths.game_party_send_match_chat.post import GamePartySendMatchChat
from openapi_client.paths.game_playerreport_reportuser.post import GamePlayerreportReportUser
from openapi_client.paths.game_relationship_clear_relationship.post import GameRelationshipClearRelationship
from openapi_client.paths.game_relationship_get_presence_data.get import GameRelationshipGetPresenceData
from openapi_client.paths.game_relationship_get_relationships.get import GameRelationshipGetRelationships
from openapi_client.paths.game_relationship_ignore.post import GameRelationshipIgnore
from openapi_client.paths.game_relationship_set_presence.post import GameRelationshipSetPresence
from openapi_client.paths.game_relationship_set_presence_property.post import GameRelationshipSetPresenceProperty


class DefaultApi(
    CommunityClanFind,
    CommunityFindAdvertisements,
    CommunityGetAchievements,
    CommunityGetAvailableAchievements,
    CommunityGetAvailableCommunityEvents,
    CommunityGetAvailableLeaderboards,
    CommunityGetAvatarStatForProfile,
    CommunityGetClanInfoFull,
    CommunityGetInventoryByProfileIds,
    CommunityGetLeaderboard2,
    CommunityGetPersonalStat,
    CommunityGetRecentMatchHistory,
    CommunityNewsGetNews,
    CommunityProxySteamUserRequest,
    GameAccountFindProfiles,
    GameAccountFindProfilesByPlatformId,
    GameAccountGetProfileName,
    GameAccountGetProfileProperty,
    GameAccountSetAvatarMetadata,
    GameAccountSetLanguage,
    GameAchievementGetAchievements,
    GameAchievementGetAvailableAchievements,
    GameAchievementSyncStats,
    GameAdvertisementFindAdvertisements,
    GameAdvertisementFindObservableAdvertisementsGet,
    GameAdvertisementFindObservableAdvertisementsPost,
    GameAdvertisementGetAdvertisements,
    GameAdvertisementGetLanAdvertisements,
    GameAdvertisementHost,
    GameAdvertisementJoin,
    GameAdvertisementLeave,
    GameAdvertisementStartObserving,
    GameAdvertisementStopObserving,
    GameAdvertisementUpdate,
    GameAdvertisementUpdatePlatformLobbyId,
    GameAdvertisementUpdateState,
    GameAdvertisementUpdateTags,
    GameAutomatch2GetAutomatchMap,
    GameAutomatch2Polling,
    GameAutomatch2StopPolling,
    GameAutomatch2UpdateStatus,
    GameAutomatchGetAutomatchMap,
    GameChallengeGetChallengeProgress,
    GameChallengeGetChallengeProgressByProfileId,
    GameChallengeGetChallenges,
    GameChallengeUpdateProgressBatched,
    GameChatDeleteOfflineMessage,
    GameChatGetChatChannels,
    GameChatGetOfflineMessages,
    GameClanApply,
    GameClanCreate,
    GameClanDisband,
    GameClanFind,
    GameClanGetClan,
    GameClanGetClanInfoFull,
    GameClanUpdate,
    GameCloudGetFileUrlGet,
    GameCloudGetFileUrlPost,
    GameCloudGetTempCredentials,
    GameCommunityEventGetAvailableCommunityEvents,
    GameCommunityEventGetEventChallengeProgress,
    GameCommunityEventGetEventStats,
    GameInvitationCancelInvitation,
    GameInvitationExtendInvitation,
    GameItemDetachItems,
    GameItemGetInventoryByProfileIds,
    GameItemGetItemBundleItemsJson,
    GameItemGetItemDefinitionsJson,
    GameItemGetItemLoadouts,
    GameItemGetItemPrices,
    GameItemGetLevelRewardsTableJson,
    GameItemGetPersonalizedSaleItems,
    GameItemGetScheduledSaleAndItems,
    GameItemMoveCharges,
    GameItemMoveItem,
    GameItemOpenItemPack,
    GameItemSignItem,
    GameItemUpdateItemAttributes,
    GameLeaderboardGetAvailableLeaderboards,
    GameLeaderboardGetLeaderboard,
    GameLeaderboardGetPartyStat,
    GameLeaderboardGetPersonalStat,
    GameLeaderboardGetRecentMatchHistoryGet,
    GameLeaderboardGetRecentMatchHistoryPost,
    GameLeaderboardGetRecentMatchSinglePlayerHistory,
    GameLeaderboardGetStatGroupsByProfileIds,
    GameLeaderboardGetStatsForLeaderboardByProfileName,
    GameLeaderboardSetAvatarStatValues,
    GameLoginLogout,
    GameLoginPlatformLogin,
    GameLoginReadSession,
    GameNewsGetNews,
    GamePartyCreateOrReportSinglePlayer,
    GamePartyFinalizeReplayUpload,
    GamePartyPeerAdd,
    GamePartyPeerUpdate,
    GamePartyReportMatch,
    GamePartySendMatchChat,
    GamePlayerreportReportUser,
    GameRelationshipClearRelationship,
    GameRelationshipGetPresenceData,
    GameRelationshipGetRelationships,
    GameRelationshipIgnore,
    GameRelationshipSetPresence,
    GameRelationshipSetPresenceProperty,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
